name: 🛠️ Builds

on:
  workflow_call:
    secrets:
      PRIVATE_EOS_SDK_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true
    inputs:
      compatibility_minimum:
        description: The minimum godot version, ('4.2' is fine, but use '4.3' will add editor help).
        default: '4.3'
        required: true
        type: string
      sconsflags:
        description: Additional compile flags to use with scons.
        default: ''
        required: false
        type: string
      temporary_artifact_suffix:
        description: Temporary artifact suffix.
        required: True
        type: string
      artifact_suffix:
        description: Additional artifact suffix.
        default: ''
        required: false
        type: string

env:
  GODOT_BRANCH_FOR_GENERATE_DOCUMENTS: 4.3-stable
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache/

jobs:
    build:
      name: ${{ matrix.icon }} ${{ matrix.identifier }} ${{ matrix.target }} (min Godot-${{ inputs.compatibility_minimum }})
      runs-on: ${{ matrix.runner }}
      defaults:
        run:
          working-directory: ${{ github.workspace }}

      strategy:
          fail-fast: false
          matrix:
              identifier: [🐧Linux-x64, 🍎Macos-Universal, 🏁Windows-x64 (clang), 🏁Windows-x86 (msvc), 🤖Android-arm64, 🤖Android-x86_64, 🤖Android-arm32, 🤖Android-x86_32]
              target: [debug, release]
              include:
                  - identifier: 🐧Linux-x64
                    runner: ubuntu-20.04
                    platform: linux
                    arch: x86_64
                    godot_editor_suffix: linux.x86_64
                    host_platform: linux
                  - identifier: 🍎Macos-Universal
                    runner: macos-latest
                    platform: macos
                    arch: universal
                    godot_editor_suffix: macos.universal
                    host_platform: macos
                  - identifier: 🏁Windows-x64 (clang)
                    runner: windows-latest
                    platform: windows
                    additional_sconsflags: use_clang_cl=yes
                    arch: x86_64
                    host_platform: windows
                    godot_editor_suffix: win64.exe
                  - identifier: 🏁Windows-x86 (msvc)
                    runner: windows-latest
                    platform: windows
                    arch: x86_32
                    godot_editor_suffix: win64.exe
                    host_platform: windows
                    force_compile_for_docs: true
                  - identifier: 🤖Android-arm64
                    runner: ubuntu-20.04
                    platform: android
                    arch: arm64
                    godot_editor_suffix: linux.x86_64
                    host_platform: linux
                    force_compile_for_docs: true
                  - identifier: 🤖Android-x86_64
                    runner: ubuntu-20.04
                    platform: android
                    arch: x86_64
                    godot_editor_suffix: linux.x86_64
                    host_platform: linux
                    force_compile_for_docs: true
                  - identifier: 🤖Android-arm32
                    runner: ubuntu-20.04
                    platform: android
                    arch: arm32
                    godot_editor_suffix: linux.x86_64
                    host_platform: linux
                    force_compile_for_docs: true
                  - identifier: 🤖Android-x86_32
                    runner: ubuntu-20.04
                    platform: android
                    arch: x86_32
                    godot_editor_suffix: linux.x86_64
                    host_platform: linux
                    force_compile_for_docs: true

      steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.x"

        - name: Set up SCons
          shell: bash
          run: |
              python -c "import sys; print(sys.version)"
              python -m pip install scons
              scons --version

        - name: Checkout project
          uses: actions/checkout@v4
          with:
              submodules: false

        - name: Checkout godot-cpp (${{ inputs.compatibility_minimum }})
          uses: actions/checkout@v4
          with:
              repository: godotengine/godot-cpp
              path: godot-cpp
              ref: godot-${{ inputs.compatibility_minimum }}-stable
              submodules: recursive

        - name: Checkout private EOS SDK repo
          uses: actions/checkout@v4
          with:
              token: ${{ secrets.PRIVATE_EOS_SDK_TOKEN }}
              repository: Daylily-Zeleen/eos-sdk
              path: thirdparty/eos-sdk
              ref: main

        - name: (Linux) Install dependencies
          if: ${{ matrix.platform == 'linux' }}
          run: |
              sudo apt-get update -qq
              sudo apt-get install -qqq build-essential pkg-config

        - name: (Linux32) Install dependencies
          if: ${{ matrix.platform == 'linux' && matrix.arch == 'x86_32' }}
          run: |
              sudo apt-get install gcc-multilib g++-multilib

        - name: (Android) Install dependencies
          if: ${{ matrix.platform == 'android' }}
          uses: nttld/setup-ndk@v1
          with:
            ndk-version: r23c
            link-to-sdk: true

        - name: Setup build cache
          uses: actions/cache@v4
          with:
              path: ${{ env.SCONS_CACHE }}
              key: ${{ matrix.identifier }}-${{ matrix.target }}-${{ matrix.arch }}-${{ inputs.compatibility_minimum }}${{ inputs.artifact_suffix }}-${{ github.branch }}-${{ github.ref }}-${{ github.sha }}
          continue-on-error: true

        - name: Compile extension
          shell: sh
          run: |
              scons target='template_${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' ${{ matrix.additional_sconsflags }} ${{ inputs.sconsflags }}

        - name: (4.3 && Debug) Generate documents and recompile extension.
          if: ${{ inputs.compatibility_minimum == '4.3' && matrix.target == 'debug' && !contains(matrix.arch, '32') }}
          uses: ./.github/actions/generate_documents_and_recompile
          with:
              godot_branch_for_generate_documents: ${{ env.GODOT_BRANCH_FOR_GENERATE_DOCUMENTS }}
              godot_editor_suffix: ${{ matrix.godot_editor_suffix }}
              sconsflags: ${{ matrix.additional_sconsflags}} ${{ inputs.sconsflags }}
              host_platform: ${{ matrix.host_platform }}
              force_compile: ${{ matrix.force_compile_for_docs }}
              platform: ${{ matrix.platform }}
              arch: ${{ matrix.arch }}

        # 不同平台的 cp 命令结果不同？？？
        - name: Copy to artifacts directory
          shell: bash
          run: |
              python ./misc/copy_dir.py ./demo/addons/ ./artifacts/GD-EOS/addons/

        - name: Upload artifact ${{ matrix.platform }}-${{ matrix.target }}-${{ matrix.arch }}-${{ inputs.compatibility_minimum }}
          uses: actions/upload-artifact@v4
          with:
              name: ${{ github.event.repository.name }}-min-godot-${{ inputs.compatibility_minimum }}${{ inputs.temporary_artifact_suffix }}-${{ matrix.platform }}-${{ matrix.target }}-${{ matrix.arch }}
              path: ./artifacts/GD-EOS/
              retention-days: 14

    merge_artifacts:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout project
          uses: actions/checkout@v4
          with:
              submodules: false

        - name: Setup version
          run: |
            echo BUILD_VERSION=$(head -n 1 ./version) >> $GITHUB_ENV

        - name: Merge Artifacts to all in one
          uses: actions/upload-artifact/merge@v4
          with:
              name: ${{ github.event.repository.name }}-${{ env.BUILD_VERSION }}-min-godot-${{ inputs.compatibility_minimum }}${{ inputs.artifact_suffix }}
              pattern: ${{ github.event.repository.name }}-min-godot-${{ inputs.compatibility_minimum }}${{ inputs.temporary_artifact_suffix }}*
              delete-merged: true
              retention-days: 90
