name: Continuous integration
on: [push, pull_request, merge_group]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  min-godot-v4_2:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.2'
      additional_sconsflags: ''
      artifact_suffix: ''

  min-godot-v4_2-AOOLU:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.2'
      additional_sconsflags: assume_only_one_local_user=yes
      artifact_suffix: _aoolu

  min-godot-v4_3:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.3'
      additional_sconsflags: ''
      artifact_suffix: ''

  min_godot-v4_3-AOOLU:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.3'
      additional_sconsflags: assume_only_one_local_user=yes
      artifact_suffix: _aoolu
