name: Continuous integration
on: [push, pull_request, merge_group]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  min-godot-v4_2-build:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.2'
      additional_sconsflags:
      artifact_suffix:

  min-godot-v4_2-AOOLU-build:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.2'
      additional_sconsflags: assume_only_one_local_user=yes
      artifact_suffix: -(aoolu)

  min-godot-v4_3-build:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.3'
      additional_sconsflags:
      artifact_suffix:

  min_godot-v4_3-AOOLU-build:
    uses: ./.github/workflows/builds.yml
    secrets: inherit
    with:
      compatibility_minimum: '4.3'
      additional_sconsflags: assume_only_one_local_user=yes
      artifact_suffix: -(aoolu)

  upload-artifact:
    # needs: [min-godot-v4_2-build, min-godot-v4_2-AOOLU-build, min-godot-v4_3-build, min_godot-v4_3-AOOLU-build]
    needs: [min-godot-v4_3-build]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compatibility_minimum: ['4.2', '4.3']
        artifact_suffix: ['', '-(aoolu)']
    steps:
      - name: test
        shell: sh
        run:
          ls ${{ github.workspace }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ github.event.repository.name }}-all-platforms-${{ env.BUILD_VERSION }}(min-godot-${{ matrix.compatibility_minimum }})${{ matrix.artifact_suffix }}-${{ github.sha }}
            path: |
                '${{ github.workspace }}/artifact-${{ matrix.compatibility_minimum }}${{ matrix.artifact_suffix }}/'
            retention-days: 90
            if-no-files-found: error